Write-Host "bing-wallpaper platform installer guide"
Write-Host ""
Write-Host "Detected platform: Windows"
Write-Host ""
Write-Host "To install the Windows version, run:"
Write-Host ""
Write-Host "  cd windows"
Write-Host "  .\install.ps1"
Write-Host ""
Write-Host "This root script is only a guide. It does not install anything."
