Write-Host "bing-wallpaper platform uninstaller guide"
Write-Host ""
Write-Host "Detected platform: Windows"
Write-Host ""
Write-Host "To uninstall the Windows version, run:"
Write-Host ""
Write-Host "  cd windows"
Write-Host "  .\uninstall.ps1"
Write-Host ""
Write-Host "This root script is only a guide. It does not uninstall anything."
